### ISSUE TITLE
clean up unused imports

### ISSUE THREAD

**Issue by coreyabshire** [claudiusptolemy/ptolemy#15]
I've started using Spyder as my Python IDE rather than Emacs, mostly just as an experiment to try new things, and in doing so noticed that it had marked several imports as unused in a file I was working on. We should go through all the code and remove all unused imports using this. This should be done in a single, separate commit, sometime before Riga 2016. Also, we should check future commits to make sure we're not adding any unused imports back in.

**Comment by ipapapa** [comment]
You may consider PyCharm :)

**Comment by coreyabshire** [comment]
:) indeed!

**Comment by coreyabshire** [comment]
Downloaded PyCharm and did a little housekeeping, including this one.
